import type { ProjectType } from '../../renderer/src/types'

export interface DetectionRule {
  id: string
  displayName: string
  category: 'GameEngine' | 'Frontend' | 'Desktop' | 'Backend' | 'Mobile' | 'AI' | 'DevOps' | 'Language' | 'Docs' | 'Monorepo'
  primaryType?: ProjectType
  platform: string[]
  language?: string
  runtime?: string
  icon: string
  checks: RuleCheck[]
}

export type RuleCheck =
  | { type: 'pathExists'; path: string; score: number }
  | { type: 'fileExists'; path: string; score: number }
  | { type: 'globExists'; pattern: string; score: number }
  | { type: 'hasDependency'; name: string; score: number }
  | { type: 'hasPythonDep'; name: string; score: number }
  | { type: 'hasCargoDep'; name: string; score: number }
  | { type: 'hasCsprojDep'; name: string; score: number }
  | { type: 'packageJsonField'; field: string; score: number }

export const RULES: DetectionRule[] = [

  // ─── Game Engines ───────────────────────────────────────────────────────────

  {
    id: 'unity',
    displayName: 'Unity',
    category: 'GameEngine',
    primaryType: 'unity',
    platform: ['Game'],
    language: 'C#',
    icon: '🎮',
    checks: [
      { type: 'pathExists', path: 'ProjectSettings', score: 40 },
      { type: 'pathExists', path: 'Assets', score: 20 },
      { type: 'fileExists', path: 'Packages/manifest.json', score: 30 },
      { type: 'globExists', pattern: '*.asmdef', score: 15 },
      { type: 'pathExists', path: 'Library', score: 10 },
    ],
  },
  {
    id: 'unreal',
    displayName: 'Unreal Engine',
    category: 'GameEngine',
    primaryType: 'unreal',
    platform: ['Game'],
    language: 'C++',
    icon: '🎮',
    checks: [
      { type: 'globExists', pattern: '*.uproject', score: 60 },
      { type: 'pathExists', path: 'Source', score: 15 },
      { type: 'pathExists', path: 'Content', score: 15 },
      { type: 'pathExists', path: 'Config', score: 10 },
    ],
  },
  {
    id: 'godot',
    displayName: 'Godot',
    category: 'GameEngine',
    primaryType: 'unknown',
    platform: ['Game'],
    icon: '🎮',
    checks: [
      { type: 'fileExists', path: 'project.godot', score: 80 },
      { type: 'globExists', pattern: '*.tscn', score: 20 },
      { type: 'globExists', pattern: '*.gd', score: 20 },
    ],
  },
  {
    id: 'gamemaker',
    displayName: 'GameMaker',
    category: 'GameEngine',
    primaryType: 'unknown',
    platform: ['Game'],
    icon: '🎮',
    checks: [
      { type: 'globExists', pattern: '*.yyp', score: 70 },
      { type: 'pathExists', path: 'rooms', score: 10 },
      { type: 'pathExists', path: 'sprites', score: 10 },
    ],
  },
  {
    id: 'rpgmaker',
    displayName: 'RPG Maker',
    category: 'GameEngine',
    primaryType: 'unknown',
    platform: ['Game'],
    icon: '🎮',
    checks: [
      { type: 'fileExists', path: 'Game.rpgproject', score: 80 },
      { type: 'pathExists', path: 'data', score: 10 },
      { type: 'pathExists', path: 'audio', score: 10 },
    ],
  },

  // ─── Desktop ────────────────────────────────────────────────────────────────

  {
    id: 'electron',
    displayName: 'Electron',
    category: 'Desktop',
    primaryType: 'node',
    platform: ['Desktop'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '⚡',
    checks: [
      { type: 'hasDependency', name: 'electron', score: 50 },
      { type: 'packageJsonField', field: 'main', score: 20 },
      { type: 'hasDependency', name: 'electron-builder', score: 10 },
      { type: 'fileExists', path: 'src/preload.ts', score: 10 },
      { type: 'fileExists', path: 'src/preload.js', score: 10 },
    ],
  },
  {
    id: 'tauri',
    displayName: 'Tauri',
    category: 'Desktop',
    primaryType: 'rust',
    platform: ['Desktop'],
    language: 'Rust',
    icon: '🦀',
    checks: [
      { type: 'pathExists', path: 'src-tauri', score: 50 },
      { type: 'fileExists', path: 'src-tauri/tauri.conf.json', score: 40 },
    ],
  },
  {
    id: 'flutter',
    displayName: 'Flutter',
    category: 'Mobile',
    primaryType: 'dart',
    platform: ['Mobile', 'Desktop', 'Web'],
    language: 'Dart',
    icon: '💙',
    checks: [
      { type: 'fileExists', path: 'pubspec.yaml', score: 30 },
      { type: 'fileExists', path: 'lib/main.dart', score: 50 },
      { type: 'pathExists', path: 'android', score: 10 },
      { type: 'pathExists', path: 'ios', score: 10 },
    ],
  },
  {
    id: 'avalonia',
    displayName: 'Avalonia',
    category: 'Desktop',
    primaryType: 'csharp',
    platform: ['Desktop'],
    language: 'C#',
    icon: '🪟',
    checks: [
      { type: 'hasCsprojDep', name: 'avalonia', score: 60 },
      { type: 'fileExists', path: 'App.axaml', score: 20 },
      { type: 'globExists', pattern: '*.axaml', score: 20 },
    ],
  },

  // ─── Frontend ───────────────────────────────────────────────────────────────

  {
    id: 'nextjs',
    displayName: 'Next.js',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '▲',
    checks: [
      { type: 'hasDependency', name: 'next', score: 40 },
      { type: 'globExists', pattern: 'next.config.*', score: 30 },
      { type: 'pathExists', path: 'app', score: 20 },
      { type: 'pathExists', path: 'pages', score: 15 },
    ],
  },
  {
    id: 'nuxt',
    displayName: 'Nuxt',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '💚',
    checks: [
      { type: 'hasDependency', name: 'nuxt', score: 50 },
      { type: 'globExists', pattern: 'nuxt.config.*', score: 30 },
    ],
  },
  {
    id: 'react',
    displayName: 'React',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '⚛',
    checks: [
      { type: 'hasDependency', name: 'react', score: 40 },
      { type: 'hasDependency', name: 'react-dom', score: 15 },
      { type: 'globExists', pattern: '*.tsx', score: 20 },
      { type: 'fileExists', path: 'src/App.tsx', score: 15 },
      { type: 'fileExists', path: 'package.json', score: 10 },
    ],
  },
  {
    id: 'vue',
    displayName: 'Vue',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '💚',
    checks: [
      { type: 'hasDependency', name: 'vue', score: 40 },
      { type: 'globExists', pattern: '*.vue', score: 30 },
      { type: 'globExists', pattern: 'vite.config.*', score: 10 },
    ],
  },
  {
    id: 'svelte',
    displayName: 'Svelte',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🔥',
    checks: [
      { type: 'hasDependency', name: 'svelte', score: 40 },
      { type: 'globExists', pattern: '*.svelte', score: 40 },
    ],
  },
  {
    id: 'sveltekit',
    displayName: 'SvelteKit',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🔥',
    checks: [
      { type: 'hasDependency', name: '@sveltejs/kit', score: 60 },
      { type: 'globExists', pattern: 'svelte.config.*', score: 20 },
    ],
  },
  {
    id: 'angular',
    displayName: 'Angular',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🔴',
    checks: [
      { type: 'fileExists', path: 'angular.json', score: 50 },
      { type: 'hasDependency', name: '@angular/core', score: 30 },
      { type: 'pathExists', path: 'src/app', score: 10 },
    ],
  },
  {
    id: 'astro',
    displayName: 'Astro',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🚀',
    checks: [
      { type: 'hasDependency', name: 'astro', score: 50 },
      { type: 'globExists', pattern: 'astro.config.*', score: 30 },
      { type: 'globExists', pattern: '*.astro', score: 20 },
    ],
  },
  {
    id: 'gatsby',
    displayName: 'Gatsby',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '💜',
    checks: [
      { type: 'hasDependency', name: 'gatsby', score: 60 },
      { type: 'globExists', pattern: 'gatsby-config.*', score: 30 },
    ],
  },
  {
    id: 'remix',
    displayName: 'Remix',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '💿',
    checks: [
      { type: 'hasDependency', name: '@remix-run/react', score: 60 },
      { type: 'hasDependency', name: '@remix-run/node', score: 60 },
      { type: 'fileExists', path: 'remix.config.js', score: 30 },
    ],
  },
  {
    id: 'solidjs',
    displayName: 'Solid.js',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🔵',
    checks: [
      { type: 'hasDependency', name: 'solid-js', score: 70 },
    ],
  },
  {
    id: 'qwik',
    displayName: 'Qwik',
    category: 'Frontend',
    primaryType: 'node',
    platform: ['Web'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '⚡',
    checks: [
      { type: 'hasDependency', name: '@builder.io/qwik', score: 70 },
    ],
  },

  // ─── Backend ────────────────────────────────────────────────────────────────

  {
    id: 'express',
    displayName: 'Express',
    category: 'Backend',
    primaryType: 'node',
    platform: ['Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🚂',
    checks: [
      { type: 'hasDependency', name: 'express', score: 60 },
      { type: 'fileExists', path: 'app.js', score: 20 },
      { type: 'fileExists', path: 'server.js', score: 20 },
    ],
  },
  {
    id: 'nestjs',
    displayName: 'NestJS',
    category: 'Backend',
    primaryType: 'node',
    platform: ['Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🐱',
    checks: [
      { type: 'hasDependency', name: '@nestjs/core', score: 60 },
      { type: 'fileExists', path: 'src/app.module.ts', score: 20 },
      { type: 'fileExists', path: 'src/main.ts', score: 10 },
    ],
  },
  {
    id: 'fastify',
    displayName: 'Fastify',
    category: 'Backend',
    primaryType: 'node',
    platform: ['Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '⚡',
    checks: [
      { type: 'hasDependency', name: 'fastify', score: 70 },
    ],
  },
  {
    id: 'hono',
    displayName: 'Hono',
    category: 'Backend',
    primaryType: 'node',
    platform: ['Server'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '🔥',
    checks: [
      { type: 'hasDependency', name: 'hono', score: 70 },
    ],
  },
  {
    id: 'spring-boot',
    displayName: 'Spring Boot',
    category: 'Backend',
    primaryType: 'java',
    platform: ['Server'],
    language: 'Java',
    runtime: 'JVM',
    icon: '🍃',
    checks: [
      { type: 'fileExists', path: 'pom.xml', score: 20 },
      { type: 'pathExists', path: 'src/main/java', score: 30 },
      { type: 'fileExists', path: 'src/main/resources/application.properties', score: 30 },
      { type: 'fileExists', path: 'src/main/resources/application.yml', score: 30 },
    ],
  },
  {
    id: 'aspnetcore',
    displayName: 'ASP.NET Core',
    category: 'Backend',
    primaryType: 'csharp',
    platform: ['Server', 'Web'],
    language: 'C#',
    icon: '🟣',
    checks: [
      { type: 'fileExists', path: 'appsettings.json', score: 40 },
      { type: 'fileExists', path: 'Program.cs', score: 20 },
      { type: 'globExists', pattern: '*.csproj', score: 20 },
      { type: 'fileExists', path: 'Startup.cs', score: 20 },
    ],
  },
  {
    id: 'blazor',
    displayName: 'Blazor',
    category: 'Frontend',
    primaryType: 'csharp',
    platform: ['Web'],
    language: 'C#',
    icon: '🟣',
    checks: [
      { type: 'globExists', pattern: '*.razor', score: 60 },
      { type: 'fileExists', path: '_Imports.razor', score: 20 },
      { type: 'globExists', pattern: '*.csproj', score: 20 },
    ],
  },
  {
    id: 'django',
    displayName: 'Django',
    category: 'Backend',
    primaryType: 'python',
    platform: ['Server', 'Web'],
    language: 'Python',
    icon: '🌿',
    checks: [
      { type: 'fileExists', path: 'manage.py', score: 40 },
      { type: 'hasPythonDep', name: 'django', score: 40 },
    ],
  },
  {
    id: 'flask',
    displayName: 'Flask',
    category: 'Backend',
    primaryType: 'python',
    platform: ['Server', 'Web'],
    language: 'Python',
    icon: '🍶',
    checks: [
      { type: 'hasPythonDep', name: 'flask', score: 50 },
      { type: 'fileExists', path: 'app.py', score: 10 },
    ],
  },
  {
    id: 'fastapi',
    displayName: 'FastAPI',
    category: 'Backend',
    primaryType: 'python',
    platform: ['Server'],
    language: 'Python',
    icon: '⚡',
    checks: [
      { type: 'hasPythonDep', name: 'fastapi', score: 60 },
    ],
  },
  {
    id: 'laravel',
    displayName: 'Laravel',
    category: 'Backend',
    primaryType: 'php',
    platform: ['Server', 'Web'],
    language: 'PHP',
    icon: '🐘',
    checks: [
      { type: 'fileExists', path: 'artisan', score: 50 },
      { type: 'fileExists', path: 'composer.json', score: 20 },
      { type: 'pathExists', path: 'app/Http', score: 20 },
      { type: 'pathExists', path: 'routes', score: 10 },
    ],
  },
  {
    id: 'symfony',
    displayName: 'Symfony',
    category: 'Backend',
    primaryType: 'php',
    platform: ['Server', 'Web'],
    language: 'PHP',
    icon: '🐘',
    checks: [
      { type: 'fileExists', path: 'symfony.lock', score: 60 },
      { type: 'fileExists', path: 'bin/console', score: 20 },
      { type: 'fileExists', path: 'composer.json', score: 10 },
    ],
  },
  {
    id: 'rails',
    displayName: 'Ruby on Rails',
    category: 'Backend',
    primaryType: 'ruby',
    platform: ['Server', 'Web'],
    language: 'Ruby',
    icon: '💎',
    checks: [
      { type: 'fileExists', path: 'config/routes.rb', score: 50 },
      { type: 'fileExists', path: 'Gemfile', score: 20 },
      { type: 'pathExists', path: 'app/controllers', score: 20 },
      { type: 'pathExists', path: 'db', score: 10 },
    ],
  },
  {
    id: 'phoenix',
    displayName: 'Phoenix',
    category: 'Backend',
    primaryType: 'unknown',
    platform: ['Server', 'Web'],
    language: 'Elixir',
    icon: '🔵',
    checks: [
      { type: 'fileExists', path: 'mix.exs', score: 50 },
      { type: 'pathExists', path: 'lib', score: 10 },
      { type: 'pathExists', path: 'priv/static', score: 30 },
    ],
  },

  // ─── Mobile ─────────────────────────────────────────────────────────────────

  {
    id: 'react-native',
    displayName: 'React Native',
    category: 'Mobile',
    primaryType: 'node',
    platform: ['Mobile'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '📱',
    checks: [
      { type: 'hasDependency', name: 'react-native', score: 60 },
      { type: 'pathExists', path: 'android', score: 20 },
      { type: 'pathExists', path: 'ios', score: 20 },
    ],
  },
  {
    id: 'expo',
    displayName: 'Expo',
    category: 'Mobile',
    primaryType: 'node',
    platform: ['Mobile'],
    language: 'TypeScript',
    runtime: 'Node.js',
    icon: '📱',
    checks: [
      { type: 'hasDependency', name: 'expo', score: 60 },
      { type: 'fileExists', path: 'app.json', score: 20 },
    ],
  },
  {
    id: 'android-native',
    displayName: 'Android',
    category: 'Mobile',
    primaryType: 'java',
    platform: ['Mobile'],
    language: 'Kotlin',
    icon: '🤖',
    checks: [
      { type: 'fileExists', path: 'app/src/main/AndroidManifest.xml', score: 60 },
      { type: 'fileExists', path: 'settings.gradle', score: 20 },
      { type: 'fileExists', path: 'build.gradle', score: 20 },
    ],
  },
  {
    id: 'ios-native',
    displayName: 'iOS',
    category: 'Mobile',
    primaryType: 'unknown',
    platform: ['Mobile'],
    language: 'Swift',
    icon: '🍎',
    checks: [
      { type: 'globExists', pattern: '*.xcodeproj', score: 60 },
      { type: 'fileExists', path: 'Info.plist', score: 20 },
      { type: 'fileExists', path: 'Package.swift', score: 20 },
    ],
  },

  // ─── AI / Data ──────────────────────────────────────────────────────────────

  {
    id: 'jupyter',
    displayName: 'Jupyter',
    category: 'AI',
    primaryType: 'ai-research',
    platform: ['Data'],
    language: 'Python',
    icon: '📓',
    checks: [
      { type: 'globExists', pattern: '*.ipynb', score: 80 },
    ],
  },
  {
    id: 'pytorch',
    displayName: 'PyTorch',
    category: 'AI',
    primaryType: 'ai-research',
    platform: ['Data'],
    language: 'Python',
    icon: '🔥',
    checks: [
      { type: 'hasPythonDep', name: 'torch', score: 60 },
    ],
  },
  {
    id: 'tensorflow',
    displayName: 'TensorFlow',
    category: 'AI',
    primaryType: 'ai-research',
    platform: ['Data'],
    language: 'Python',
    icon: '🧠',
    checks: [
      { type: 'hasPythonDep', name: 'tensorflow', score: 60 },
      { type: 'hasPythonDep', name: 'tensorflow-gpu', score: 60 },
    ],
  },
  {
    id: 'langchain',
    displayName: 'LangChain',
    category: 'AI',
    primaryType: 'ai-research',
    platform: ['Data'],
    language: 'Python',
    icon: '🦜',
    checks: [
      { type: 'hasPythonDep', name: 'langchain', score: 60 },
    ],
  },
  {
    id: 'huggingface',
    displayName: 'HuggingFace',
    category: 'AI',
    primaryType: 'ai-research',
    platform: ['Data'],
    language: 'Python',
    icon: '🤗',
    checks: [
      { type: 'hasPythonDep', name: 'transformers', score: 60 },
      { type: 'hasPythonDep', name: 'datasets', score: 30 },
    ],
  },

  // ─── DevOps ─────────────────────────────────────────────────────────────────

  {
    id: 'docker',
    displayName: 'Docker',
    category: 'DevOps',
    platform: ['DevOps'],
    icon: '🐳',
    checks: [
      { type: 'fileExists', path: 'Dockerfile', score: 40 },
      { type: 'fileExists', path: 'docker-compose.yml', score: 40 },
      { type: 'fileExists', path: 'docker-compose.yaml', score: 40 },
      { type: 'fileExists', path: '.dockerignore', score: 10 },
    ],
  },
  {
    id: 'kubernetes',
    displayName: 'Kubernetes',
    category: 'DevOps',
    platform: ['DevOps'],
    icon: '☸️',
    checks: [
      { type: 'pathExists', path: 'k8s', score: 40 },
      { type: 'fileExists', path: 'deployment.yaml', score: 30 },
      { type: 'fileExists', path: 'service.yaml', score: 20 },
      { type: 'fileExists', path: 'Chart.yaml', score: 20 },
    ],
  },
  {
    id: 'terraform',
    displayName: 'Terraform',
    category: 'DevOps',
    platform: ['DevOps'],
    language: 'HCL',
    icon: '🏗️',
    checks: [
      { type: 'globExists', pattern: '*.tf', score: 60 },
      { type: 'pathExists', path: '.terraform', score: 20 },
      { type: 'fileExists', path: 'terraform.tfvars', score: 20 },
    ],
  },
  {
    id: 'github-actions',
    displayName: 'GitHub Actions',
    category: 'DevOps',
    platform: ['DevOps'],
    icon: '⚙️',
    checks: [
      { type: 'pathExists', path: '.github/workflows', score: 70 },
      { type: 'pathExists', path: '.github', score: 20 },
    ],
  },

  // ─── Monorepo ───────────────────────────────────────────────────────────────

  {
    id: 'nx',
    displayName: 'Nx',
    category: 'Monorepo',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    runtime: 'Node.js',
    icon: '🏢',
    checks: [
      { type: 'fileExists', path: 'nx.json', score: 70 },
    ],
  },
  {
    id: 'turborepo',
    displayName: 'Turborepo',
    category: 'Monorepo',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    runtime: 'Node.js',
    icon: '🏢',
    checks: [
      { type: 'fileExists', path: 'turbo.json', score: 70 },
    ],
  },
  {
    id: 'lerna',
    displayName: 'Lerna',
    category: 'Monorepo',
    primaryType: 'node',
    platform: ['Web', 'Server'],
    runtime: 'Node.js',
    icon: '🏢',
    checks: [
      { type: 'fileExists', path: 'lerna.json', score: 70 },
    ],
  },

  // ─── Documentation / CMS ────────────────────────────────────────────────────

  {
    id: 'vitepress',
    displayName: 'VitePress',
    category: 'Docs',
    primaryType: 'docs',
    platform: ['Web'],
    runtime: 'Node.js',
    icon: '📚',
    checks: [
      { type: 'hasDependency', name: 'vitepress', score: 60 },
      { type: 'pathExists', path: '.vitepress', score: 60 },
    ],
  },
  {
    id: 'docusaurus',
    displayName: 'Docusaurus',
    category: 'Docs',
    primaryType: 'docs',
    platform: ['Web'],
    runtime: 'Node.js',
    icon: '📚',
    checks: [
      { type: 'hasDependency', name: '@docusaurus/core', score: 60 },
      { type: 'globExists', pattern: 'docusaurus.config.*', score: 50 },
    ],
  },
  {
    id: 'jekyll',
    displayName: 'Jekyll',
    category: 'Docs',
    primaryType: 'docs',
    platform: ['Web'],
    language: 'Ruby',
    icon: '📚',
    checks: [
      { type: 'fileExists', path: '_config.yml', score: 40 },
      { type: 'pathExists', path: '_posts', score: 30 },
      { type: 'pathExists', path: '_layouts', score: 20 },
    ],
  },
  {
    id: 'obsidian',
    displayName: 'Obsidian Vault',
    category: 'Docs',
    primaryType: 'docs',
    platform: ['Desktop'],
    icon: '🔮',
    checks: [
      { type: 'pathExists', path: '.obsidian', score: 80 },
    ],
  },
  {
    id: 'hugo',
    displayName: 'Hugo',
    category: 'Docs',
    primaryType: 'docs',
    platform: ['Web'],
    language: 'Go',
    icon: '📚',
    checks: [
      { type: 'pathExists', path: 'archetypes', score: 40 },
      { type: 'pathExists', path: 'themes', score: 20 },
      { type: 'fileExists', path: 'hugo.toml', score: 40 },
      { type: 'fileExists', path: 'config.toml', score: 10 },
    ],
  },

  // ─── Language catch-alls ─────────────────────────────────────────────────────

  {
    id: 'go',
    displayName: 'Go',
    category: 'Language',
    primaryType: 'go',
    platform: ['Server'],
    language: 'Go',
    icon: '🐹',
    checks: [
      { type: 'fileExists', path: 'go.mod', score: 60 },
      { type: 'fileExists', path: 'go.sum', score: 10 },
      { type: 'globExists', pattern: '*.go', score: 20 },
    ],
  },
  {
    id: 'java',
    displayName: 'Java',
    category: 'Language',
    primaryType: 'java',
    platform: ['Server'],
    language: 'Java',
    runtime: 'JVM',
    icon: '☕',
    checks: [
      { type: 'fileExists', path: 'pom.xml', score: 30 },
      { type: 'pathExists', path: 'src/main/java', score: 40 },
      { type: 'globExists', pattern: '*.java', score: 20 },
    ],
  },
  {
    id: 'kotlin',
    displayName: 'Kotlin',
    category: 'Language',
    primaryType: 'java',
    platform: ['Server', 'Mobile'],
    language: 'Kotlin',
    runtime: 'JVM',
    icon: '🟣',
    checks: [
      { type: 'globExists', pattern: '*.kt', score: 40 },
      { type: 'globExists', pattern: 'build.gradle.kts', score: 30 },
    ],
  },
  {
    id: 'scala',
    displayName: 'Scala',
    category: 'Language',
    primaryType: 'java',
    platform: ['Server'],
    language: 'Scala',
    runtime: 'JVM',
    icon: '🔴',
    checks: [
      { type: 'fileExists', path: 'build.sbt', score: 70 },
      { type: 'globExists', pattern: '*.scala', score: 30 },
    ],
  },
  {
    id: 'php',
    displayName: 'PHP',
    category: 'Language',
    primaryType: 'php',
    platform: ['Server', 'Web'],
    language: 'PHP',
    icon: '🐘',
    checks: [
      { type: 'fileExists', path: 'composer.json', score: 40 },
      { type: 'fileExists', path: 'index.php', score: 20 },
      { type: 'globExists', pattern: '*.php', score: 20 },
    ],
  },
  {
    id: 'ruby',
    displayName: 'Ruby',
    category: 'Language',
    primaryType: 'ruby',
    platform: ['Server'],
    language: 'Ruby',
    icon: '💎',
    checks: [
      { type: 'fileExists', path: 'Gemfile', score: 40 },
      { type: 'globExists', pattern: '*.rb', score: 20 },
      { type: 'fileExists', path: 'Gemfile.lock', score: 10 },
    ],
  },
  {
    id: 'dart',
    displayName: 'Dart',
    category: 'Language',
    primaryType: 'dart',
    platform: ['Server', 'Web'],
    language: 'Dart',
    icon: '💙',
    checks: [
      { type: 'fileExists', path: 'pubspec.yaml', score: 40 },
      { type: 'globExists', pattern: '*.dart', score: 30 },
    ],
  },
  {
    id: 'swift',
    displayName: 'Swift',
    category: 'Language',
    primaryType: 'unknown',
    platform: ['Mobile', 'Desktop', 'Server'],
    language: 'Swift',
    icon: '🍎',
    checks: [
      { type: 'fileExists', path: 'Package.swift', score: 70 },
      { type: 'globExists', pattern: '*.swift', score: 30 },
    ],
  },
  {
    id: 'deno',
    displayName: 'Deno',
    category: 'Language',
    primaryType: 'node',
    platform: ['Server'],
    language: 'TypeScript',
    runtime: 'Deno',
    icon: '🦕',
    checks: [
      { type: 'fileExists', path: 'deno.json', score: 70 },
      { type: 'fileExists', path: 'deno.jsonc', score: 70 },
      { type: 'fileExists', path: 'deno.lock', score: 20 },
    ],
  },
  {
    id: 'cpp',
    displayName: 'C/C++',
    category: 'Language',
    primaryType: 'cpp',
    platform: ['Desktop', 'Server'],
    language: 'C++',
    icon: '⚙️',
    checks: [
      { type: 'fileExists', path: 'CMakeLists.txt', score: 40 },
      { type: 'globExists', pattern: '*.cpp', score: 25 },
      { type: 'globExists', pattern: '*.cc', score: 25 },
      { type: 'globExists', pattern: '*.h', score: 15 },
    ],
  },
  {
    id: 'zig',
    displayName: 'Zig',
    category: 'Language',
    primaryType: 'unknown',
    platform: ['Desktop', 'Server'],
    language: 'Zig',
    icon: '⚡',
    checks: [
      { type: 'fileExists', path: 'build.zig', score: 80 },
    ],
  },
  {
    id: 'elixir',
    displayName: 'Elixir',
    category: 'Language',
    primaryType: 'unknown',
    platform: ['Server'],
    language: 'Elixir',
    icon: '💜',
    checks: [
      { type: 'fileExists', path: 'mix.exs', score: 60 },
      { type: 'globExists', pattern: '*.ex', score: 20 },
    ],
  },
  {
    id: 'haskell',
    displayName: 'Haskell',
    category: 'Language',
    primaryType: 'unknown',
    platform: ['Server'],
    language: 'Haskell',
    icon: '🟣',
    checks: [
      { type: 'globExists', pattern: '*.cabal', score: 70 },
      { type: 'fileExists', path: 'stack.yaml', score: 50 },
    ],
  },

  // ─── Node.js / Rust / Python catch-alls ────────────────────────────────────

  {
    id: 'node',
    displayName: 'Node.js',
    category: 'Language',
    primaryType: 'node',
    platform: ['Server', 'Web'],
    language: 'JavaScript',
    runtime: 'Node.js',
    icon: '🟢',
    checks: [
      { type: 'fileExists', path: 'package.json', score: 10 },
    ],
  },
  {
    id: 'rust',
    displayName: 'Rust',
    category: 'Language',
    primaryType: 'rust',
    platform: ['Server'],
    language: 'Rust',
    icon: '🦀',
    checks: [
      { type: 'fileExists', path: 'Cargo.toml', score: 40 },
    ],
  },
  {
    id: 'python',
    displayName: 'Python',
    category: 'Language',
    primaryType: 'python',
    platform: ['Server'],
    language: 'Python',
    icon: '🐍',
    checks: [
      { type: 'fileExists', path: 'requirements.txt', score: 20 },
      { type: 'fileExists', path: 'pyproject.toml', score: 20 },
    ],
  },
]
