import fs from 'fs'
import path from 'path'
import type { FileNode } from '../renderer/src/types'

const EXCLUDED_DIRS = new Set([
  'node_modules', '.git', '.hg', '.svn',
  'dist', 'build', 'out', '.next', '.nuxt', '.svelte-kit',
  '__pycache__', '.pytest_cache', '.mypy_cache',
  '.turbo', 'coverage', '.nyc_output',
  '.DS_Store', 'Thumbs.db'
])

// Dirs generated by Unity — large, no markdown content
const UNITY_EXCLUDED = new Set(['Library', 'Temp', 'Logs', 'obj', 'Build', 'Builds'])

function isUnityProject(dirPath: string): boolean {
  try {
    const entries = fs.readdirSync(dirPath)
    return entries.includes('Assets') && entries.includes('ProjectSettings')
  } catch {
    return false
  }
}

function buildFileTreeInner(
  dirPath: string,
  extraExcluded: Set<string>
): FileNode {
  const stat = fs.statSync(dirPath)
  const name = path.basename(dirPath)

  if (!stat.isDirectory()) {
    return { name, path: dirPath, isDir: false, modifiedAt: stat.mtimeMs }
  }

  let entries: fs.Dirent[] = []
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true })
  } catch { /* skip dirs without permission */ }

  const visible = entries.filter(
    (e) => !e.name.startsWith('.') && !EXCLUDED_DIRS.has(e.name) && !extraExcluded.has(e.name)
  )
  const dirs = visible.filter((e) => e.isDirectory())
  const files = visible.filter((e) => !e.isDirectory() && e.name.endsWith('.md'))

  const children: FileNode[] = [
    // Only include dirs that contain at least one md file (recursively)
    ...dirs
      .map((d) => buildFileTreeInner(path.join(dirPath, d.name), extraExcluded))
      .filter((child) => !child.isDir || (child.mdCount ?? 0) > 0),
    ...files.map((f) => {
      const fp = path.join(dirPath, f.name)
      try {
        const s = fs.statSync(fp)
        return { name: f.name, path: fp, isDir: false, modifiedAt: s.mtimeMs }
      } catch {
        return { name: f.name, path: fp, isDir: false, modifiedAt: 0 }
      }
    })
  ]

  const mdCount = countMd(children)
  return { name, path: dirPath, isDir: true, children, modifiedAt: stat.mtimeMs, mdCount }
}

export function buildFileTree(dirPath: string): FileNode {
  const extraExcluded = isUnityProject(dirPath) ? UNITY_EXCLUDED : new Set<string>()
  return buildFileTreeInner(dirPath, extraExcluded)
}

function countMd(nodes: FileNode[]): number {
  return nodes.reduce((acc, n) => {
    if (!n.isDir) return acc + 1
    return acc + (n.mdCount ?? 0)
  }, 0)
}
